//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.20 at 10:32:29 PM ART 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://wsaa.view.sua.dvadac.desein.afip.gov", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.yacardev.afip.wsaa.soap.wsdl;
